---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: beep-staging
spec:
  encryptedData:
    postgres-password: AgAli1xx0oClQFCyTaoxeOA0F7HFt8Zz6++obcqE5dfCByahDKZknBBZ2uk8xWhor6ggmNegjlRyXRbCa6giUcigMLjKq6s/uYdjgIjc5busTF6iN6OA5UkXwlouo9LesbJgKAivKV9lZt57IkszdgqHCQHuhSTC4z54lWDV8X/14x5+q86ymPQN4aNp339TC5EhyJtYFPOiaQh/8ewv1zA2n5rVcarHMvdBHhRA85V8p2Mt+jrxELsXM8cQllgmOt+JelkE0cKwcY2i/kmyyZdRr/41NrhmKJafYVmQfABzQKiAjy7yrRoXdm0BBJpdZuC2ruXpzA9ZOALj1B7oHYn/rP9qSEomGx0osdtPTuswpsUBOFvCKXTQ07s8Wd+Xq7DAv2Tf8AEfaTv8jwVpWk+YzfiyPZZkdy4cOelOvInJjdAaQBkUzPw4hON9jJbZ7LBaXuAgUd1aNVkPrcAja4Cl6JFwY0LHZJ2ZV38CUj9HriGEXLhy7BOONn1EWCbm2TDPBmLhxHYwxVzhf0Z0taMFBOMN1+L/B+OMRo/dgCIiHdtEe2U+5Wt5T97e3uyRt76lY2bmqvtPTWVZBD3f1VXvDIsXymqZMg45rj3w6tRgSkrM6l3b4ri8Uh+nQP/5VBmi3ISPT+9M8D7oSU5l7JGls8hQ+104T9U/89SETIUtgrqqLOa4tiQJz7z2UzkHOZfHG89zHCF3O+MjNWhU5BnPe/m1rJY=
  template:
    metadata:
      name: postgresql-secret
      namespace: beep-staging
