---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: beep-development
spec:
  encryptedData:
    minio-password: AgCBxuwfXefwzL6dilbrma5zLKw1KycQu7UkjJN5lPxCo0oT0e0SDWQOMduF9u7oFi+mxifC4lBBDU1I62hSu/XzCPz+7H4oQGqhvRqapXGe4MmwBRteTbCGCUpBur7J88f34se/PW6bXgBN43HScFr/CGiYYQyqsnEUG8Kvm5iaXDFVKtzALRqjZZWeeaAWCTGj7tVfiMS0Ory2J+6Ze89td2ITWVu1HH7fhMWE7XAFaqZNKEHx0LF5T9eUJjoyhbnDcOTwnNsti/q+KvMeESNkwhzQwkKlHSCASZ9VU4SH4vpwfjiA/+mrsCHk98pEtwa3HFENpFsx1cxJpsTwdN/HVyCuWpx0jq+9xy1MVTy7QhzPjY1B+9ItjGB8ks4p1c17kw5AK12VRnI2RTuurUgQ2rvEp/ECJcNWbPRTm8s1OSMeZ9+tXa0qvKOyI0zUVlP7KR5EUKTc2p5ozZvGauKmvyid6KD31EgSpay4o7d7vR6xp1EcHw4o9HnGCae5krPNc+KYllJSRZXYciInEDJYPvxtc1vEsLI30Aci/2qcUdSOOr4ef7EHrbP6aUSjeVlw/O95GW/d0I6ZX2ZE39GtBNgnyzRzScTwyERZbmXr8C5jE+k92KowvelEYqoM5eikHN6zcWce7RbLrM9csKk2Zc603EU2AbWiW94LAiH/qVwOGTgI0rYr4hb+3Hv8uaPowEgmGwh3Ij9Ri4BEQiO7I8dce4xtGMM=
    minio-user: AgB9PsoPs00wnnXmxGLME8lHQE5r45cFLf2b4r5cUj7yp+5x+BzkvlA59kOfyll7AJ4kltNBSjn8PeiOX10YMuJT701fPscNKfmIuK/T5OcnXLbcVbYBBYEy22oANQjAONl1ccviIzG6Dx9STmP6dR60B3wu5mzZjOFKgkbfBXCGnl9Nynt4Qmvi0NU3Me9W4LlEpaP+GcGTJqMxRY26FaqBdZSnLtWTukzFfEMwAqv0/nQEUfiTFDe0s1xCvP3h4tV3XGsueG8NMxmvr6wGLJQuFgRaU7zNGGM3lhsEWqJ/lXhom7JfBBY/K9GeEmLkHuX0wgcHe75j73SA4y1tk5aTzNTSVmapDe9uAuMFrFrb0h3a7wWz3XJKuLZ4m0fhW1Vq6FRtz1M7nW04nuRSLG6IFlu7X/wGwRkcWayp37uKzXPNU5WxSOaA7WB4C/ZobX1fqt3PLl/uclgJ5ZA/MUVsX7CNI74ttdyIxHs+k1EwsHt9ZA18hIZbg3Ev4o7uDPNgEzUvR/DLem3nCRHYwwRfyoB8qHcA3oJ6vIZeKoicGyO0T0huu9B+p+E9I3WHzhyefX4bXy66oCgj+TGi1u5q6pxrSomAg14lW0v0aq64OyuynsmAIBQE7LYnE8T3cjJP76c3QPLItRb3xrn3IZLpBh7LyDEZqEfLYjtmnNSfZcQ8NeYRHNsnfb5O5cJAJBY9M/6J9cQ8iakMzg==
  template:
    metadata:
      name: minio-secret
      namespace: beep-development
