---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: beep-development
spec:
  encryptedData:
    redis-password: AgC95Nck/xTdeLScPxFJr7ZDBSRmgCHLqWBWKBauG/yc74+xvH5tYPkuZ+uwoSmv8SfOHWr3hfAuy7+mtPSXIIAgJc87B1CVRGgEa/CBJlwsPKZDgtgalG6lULKDibhsjDUuzEcBhN5bQ6c5T3Fklg4Kr1rmlrBS+jgznPSQGBFMl37pVlOgQLIXODSsFjoPrPXWzFAmKKG8Ww113qIHe2w9W/ffs2P5tWKkUmz2TowC5WTMwnHtK9PIYE5qIgBINgO/T2enP0ueY/tK54Ml/Ge/mVkcnyX+dRebFOt/CYMHQ6zZ1xJZYgQJsRr6hFiUUmQN9+rG5u4bhx/dkIP+1mCg0DnWlWxHrZjvFol3fcY/5Z2DSM7uczQn9bkHiC/lCa1zeLCBFdA2C8GAILaLJYaZCm9TZ27MmejPew034L+NjhL+0pf463D+ivcrAUZiAvQ+KeJJBUqpjGmQEX2rDXOKKsbDIJ2yzGoUNbUMCvDvEz49eeijdQj5tWYWFRlg77AsFuhfpbBLRdQerGOV18/qx+A29Md0MqAKaLupNdOppp4YowinUveOLOM6LAqGKYni3abRh9R4tnJGaqM3bE/twgwa9VDq16q0n6Jo9/fvg1wK9/C5zSkE4q9n8gheJRqMNZTwpknkqm5ZmCJzMKit/CtFeGIAfkTlbXByK3GADRlDn2WmfsP8pXXP7xg2bksjYN2QWaGTsmZPqt1FRXiweZfbgpZBWZk=
  template:
    metadata:
      name: redis-secret
      namespace: beep-development
