---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: beep-production
spec:
  encryptedData:
    minio-password: AgAkIQpv3rvPBEZv3AvntmUShe0XYSJwSCS5qxy8F+rxc1a6GArk4LD7CPHcz/L/NwudA/vvP6ls0/bJWIDIcQFnZQc6bZuzUWz3h8DeE/jEvwSpfdIQY1GZ5Zl81EF1Xka9okjTtmWaBCahobVYyIoL1o57jUQTGhDLyO51glPR6djD/29RQOQ3EAeEI6ajRUVQOVv7adKmuQF/vvSCBUpcALPTFy38mZwC7CBRTEVnHDC7lXXhDacMdIrsrYjnCkQlV+OMAsKr22rJ+zXNZFmP+Lo94tADp/k7pdBhvz3mR5hmxOuHOkd40GlTZYPUzb2aJrB4K/lx7ndHfmIjKY1Bj8KqF3tk2Kbn9sSvgXqaeXGBxtfV7143hEIekzCcPaTxIqA7O2cZSjX4RuOijmXf09MMVY4pbo3fPZsnSXbzgUJ/lOXv5E/dtd8InQnSeoBwx7GGYBKH4pO+DYQq6TNsn4qReBKzIcQcY5e4dwHjUxJyvqPnj3TSh1frnQDdzUk1qquDDPMtf9Sli2IGKUKSDInNEROGYVcYCR03YbqirqaDoFilqs/DysAidbhNm+cT+osMtMhV4QVHShhqBsBM3BniudsqtCaXfFFU6U5Tlu0i5C0Lz4bhmWxeEQw45ayhUMLc8nGbZoR2/h8aVU8vzUxzf7UfmH4KLwUNwCNLm1X7I0w/llPKIq1bp/6h8mVt+orUPnMmxRuMqyanPPlHn1dZgQ==
    minio-user: AgBtLiBR5RQVQkeBMzVJUUSnlVlkz8UEYWjR7amwyAUK4WhQ3zm9CPn3lkerZowQMEX2Lm+lQ+sQQND9VhHlweUpKZRb23qsjOIQMIlhy+04yz5GYaMfa+8+xBpkCjhXcw+JceWHX/i0X0jECtgyMwCoAolcdPYbtl/Y/I6CNJa/2CSnC3jhwvah+Oi6mQ/kcs9jqoUKQO8kmM6rm0jvYoBd9xbDWFg9zUr46Ku8p/T7bt+p3Be9BmosvNpVH0CRikuAPRQf0V1btJLtUlIz1RQW9oODcHbwx8nVMhtnjnHqNAuj/yYNZeC6CYsPqWLzkOUupCINhv8eV+jqCQVsRJA1ILIDSnFGNAHgJral2zy0qb0An6RKNMdz0xIBPYx6zZc7kaT9d5bJOeo2R4qyXLfFIhzT65wJhGq+2YGVyrsHiUGcaQYIn1p3h/Ow0UZQxlbzSpJuGAJVGxHgzeyNw46x4zDcY/KH4iPzj3ZAj2L1k3LAyUkOVxRkYvNvM+wsZmY+weqXgIGRySrzK6nxD/Z3ZVirf+rMEseuQETzVk7EZLelI1Z8YDAqzOf30rpNKpVpW4baqBs5L73/WHfd0S9klAq/Sjz4gqBIPNfrnC5PQFEyIQzn9VR5eCh48wqRK9ppQJB987i5DctOn+wpxn0gwYHu4RReIUvgo3NKCcguR/CuzbpydcwVmz8402Aqy7PSlBeTAfoHoIainA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: beep-production
